source "https://rubygems.org"

# use local theme gem for testing
gem "minimal-mistakes-jekyll", path: "../"
group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.0'
  gem "minimal-mistakes-jekyll"
  gem "kramdown-parser-gfm"
  gem "webrick", "~> 1.8"
end

